brivdarcy/beach-buoys

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

J'ai fait la homepage mis sous home.html.erb pouvez vous jeter un coup d oeil svp

first try homepage in banner

---

.gitignore
Gemfile
Gemfile.lock
app/views/buoys/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20200817145603_create_active_storage_tables.active_storage.rb
db/schema.rb
db/seeds.rb

Cloudinary

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

j'ai fait des modoifications de styles

second midification

---

app/views/pages/home.html.erb

link to index modified

---

db/seeds.rb

finish seed

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/views/buoys/show.html.erb

improving show style

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_buoy_show.scss
app/assets/stylesheets/pages/_index.scss
app/views/buoys/show.html.erb

adding a form to the show

---

app/controllers/buoys_controller.rb
app/models/buoy.rb
app/views/buoys/_form.html.erb
app/views/buoys/index.html.erb
app/views/buoys/show.html.erb
db/migrate/20200818092552_add_columns_to_buoys.rb
db/schema.rb

rajout de 2 colonnes dans table Buoys : 
address
person_number
Ajout des validations dans model Buoy
Ajout des champs dans show & index & form (edit/new)

Change db buoys

---

app/controllers/bookings_controller.rb
app/controllers/buoys_controller.rb
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
app/views/buoys/show.html.erb
config/routes.rb
test/controllers/bookings_controller_test.rb

completed bookings

---

app/controllers/buoys_controller.rb
app/views/buoys/show.html.erb
db/migrate/20200818114650_add_dates_to_booking.rb
db/schema.rb

add start_date and end_date to model bookings
add simple_form_for to buoy show

add dates columns to booking model

---

app/views/buoys/show.html.erb

fixing modal

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_buoy-index.scss
app/assets/stylesheets/pages/_index.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

footer on all pages and at the back

fixing footer at the back of page

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_buoy-index.scss
app/assets/stylesheets/pages/_buoy_show.scss
app/views/buoys/index.html.erb

improve style of cards in buoys index

improving index of buoys

---

config/routes.rb

sortie la route destroy nestée par erreur

modify routes on destroy

---

app/javascript/plugins/flatpickr.js
app/views/buoys/show.html.erb

Affichage dynamique du prix et de la durée du booking sous le calendrier

calendar with dynamic display of price & dates done

---

app/views/buoys/_form.html.erb
app/views/buoys/edit.html.erb
app/views/buoys/index.html.erb
app/views/buoys/new.html.erb
app/views/buoys/show.html.erb

user adapting

---

app/assets/stylesheets/components/_button.scss
app/views/bookings/show.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/pages/profile.html.erb

correction de la typo "s'inscrire"
correction des liens "retour page précédente"

correction des liens

---

app/views/buoys/show.html.erb

adding a delete button for the user to the show

adding button delete

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
config/initializers/geocoder.rb

Ai fait mofifications du titre de la homepage et du footer

text in english is modified

---

app/views/pages/home.html.erb

Ai rajouté un espace entre sur et bouée

espace rajouté dans titre

---

app/views/pages/profile.html.erb

ajouté les cards de bouées louées au profil de l'user

Modify profile

---

db/seeds.rb
yarn.lock

Ai modifié le nom de chaque card en français

Modify cards name

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/application_controller.rb
app/views/shared/_navbar.html.erb

update picutre when editing a profile ===> ok

avatar update

---

app/controllers/bookings_controller.rb
app/controllers/buoys_controller.rb
app/views/buoys/show.html.erb
app/views/pages/profile.html.erb

add resas on the profile of user

Add resas profile

---

app/assets/stylesheets/pages/_profile.scss
app/controllers/bookings_controller.rb
app/views/buoys/show.html.erb
app/views/pages/profile.html.erb

changer le path de la resa et le style des cartes sur le profil

changing button path and card style

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/buoys_controller.rb
app/views/buoys/index.html.erb
app/views/pages/home.html.erb

Changing links

---

app/assets/stylesheets/application.scss
app/controllers/buoys_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/models/buoy.rb
app/views/bookings/show.html.erb
app/views/buoys/index.html.erb
app/views/devise/registrations/new.html.erb
config/initializers/geocoder.rb
db/migrate/20200820085058_add_coordinates_to_buoys.rb
db/schema.rb
package.json
yarn.lock

installation map sur index

---

app/assets/stylesheets/components/_card.scss
app/controllers/reviews_controller.rb
app/views/buoys/show.html.erb

add style to the review cards

---

app/javascript/plugins/flatpickr.js
app/views/buoys/show.html.erb

not display date and price while not selected

display none

---

app/assets/stylesheets/pages/_profile.scss
app/controllers/pages_controller.rb
app/models/user.rb
app/views/pages/profile.html.erb

page profile ok 
TODO: revoir bouton retour

Profil revu

---

app/views/buoys/show.html.erb
config/initializers/geocoder.rb

change the show when the owner looks at his buoy

Modify buoy show

---

app/assets/stylesheets/pages/_buoy-index.scss
app/views/buoys/index.html.erb

elargissement de la map ce que je vous ai montré....

elargissement map sur index
